services:
  - type: web
    name: eventintel
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: EventIntel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: SESSION_DOMAIN
        value: ""
      - key: SESSION_SECURE_COOKIE
        value: "false"
      - key: SESSION_SAME_SITE
        value: lax
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "false"
      - key: SESSION_SAME_SITE
        value: lax
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
